# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 23:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('announce', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='announce')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'articles',
                'verbose_name': 'article',
            },
        ),
    ]
