# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text'),
        ),
    ]
