# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.Ticket', verbose_name='ticket'),
            preserve_default=False,
        ),
    ]
