# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_comment_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_read_by_staff',
            field=models.BooleanField(default=False, verbose_name='is read by staff'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_read_by_user',
            field=models.BooleanField(default=True, verbose_name='is read by user'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 9, 8, 30, 3, 416760, tzinfo=utc), verbose_name='updated at'),
            preserve_default=False,
        ),
    ]
