# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20160109_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='comment'),
        ),
    ]
