# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='superbanner', verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='title')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
            ],
            options={
                'verbose_name_plural': 'superbanners',
                'verbose_name': 'superbanner',
                'ordering': ['ordering'],
            },
        ),
    ]
