# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 22:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superbanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbanner',
            name='button_label',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='button label'),
        ),
        migrations.AddField(
            model_name='superbanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='button link'),
        ),
        migrations.AddField(
            model_name='superbanner',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='text'),
        ),
    ]
