# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:13
from __future__ import unicode_literals

import addresspicker.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20160106_1850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shop',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='map_point',
            field=addresspicker.fields.AddressPickerField(blank=True, max_length=64, null=True, verbose_name='on map'),
        ),
    ]
