# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20160106_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='', help_text='user for create url', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
