# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20160110_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='browser_title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='browser title'),
        ),
        migrations.AddField(
            model_name='shop',
            name='meta_description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='meta description'),
        ),
    ]
