# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_geoip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('region', models.ManyToManyField(blank=True, related_name='location', to='django_geoip.Region', verbose_name='region contains')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['name'],
            },
        ),
    ]
