# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_region_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
    ]
