# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160110_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('article', models.CharField(max_length=16, verbose_name='article')),
                ('price', models.FloatField(verbose_name='price')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'catalog items',
                'verbose_name': 'catalog item',
            },
        ),
    ]
