# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20160109_1834'),
        ('catalog', '0006_auto_20160110_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='shop'),
            preserve_default=False,
        ),
    ]
