# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_item_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
