# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20160110_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='old price'),
        ),
    ]
