# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_item_old_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated_at'], 'verbose_name': 'catalog item', 'verbose_name_plural': 'catalog items'},
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 12, 10, 29, 26, 133381, tzinfo=utc), verbose_name='updated at'),
            preserve_default=False,
        ),
    ]
