# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160112_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCustomProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='property name')),
                ('value', models.CharField(max_length=2048, verbose_name='property value')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='catalog item')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'verbose_name': 'property',
                'ordering': ['ordering'],
            },
        ),
    ]
