# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160112_1651'),
        ('catalog', '0012_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='size_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SizeSet', verbose_name='size set'),
        ),
    ]
