# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160112_1651'),
        ('catalog', '0013_category_size_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='vendor size'),
        ),
        migrations.AddField(
            model_name='item',
            name='standard_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Size', verbose_name='standard size'),
        ),
    ]
