# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160112_1651'),
        ('catalog', '0015_item_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=16, null=True, verbose_name='vendor size')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Color', verbose_name='color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item', verbose_name='catalog item')),
                ('standard_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Size', verbose_name='standard size')),
            ],
            options={
                'verbose_name': 'SKU',
                'ordering': ['color', 'size'],
            },
        ),
    ]
