# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_itemsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsku',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
