# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20160112_1651'),
        ('catalog', '0017_itemsku_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSKUSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=16, verbose_name='vendor size')),
            ],
            options={
                'verbose_name': 'SKU size',
                'ordering': ['size'],
            },
        ),
        migrations.AlterModelOptions(
            name='itemsku',
            options={'ordering': ['color'], 'verbose_name': 'SKU'},
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='size',
        ),
        migrations.RemoveField(
            model_name='itemsku',
            name='standard_size',
        ),
        migrations.AddField(
            model_name='itemskusize',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ItemSKU'),
        ),
        migrations.AddField(
            model_name='itemskusize',
            name='standard_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Size', verbose_name='standard size'),
        ),
    ]
