# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20160113_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSKUPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='catalog', verbose_name='image')),
                ('ordering', models.IntegerField(default=100, verbose_name='ordering')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ItemSKU')),
            ],
            options={
                'ordering': ['ordering'],
                'verbose_name': 'photo',
                'abstract': False,
                'verbose_name_plural': 'photos',
            },
        ),
    ]
