# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_itemskuphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku_allowed',
            field=models.BooleanField(default=True, verbose_name='sku allowed'),
        ),
    ]
