# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20160119_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemphoto',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='itemskuphoto',
            options={'ordering': ['ordering', 'id'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AddField(
            model_name='category',
            name='filter_color_allowed',
            field=models.BooleanField(default=True, verbose_name='filter color allowed'),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_fabric_allowed',
            field=models.BooleanField(default=True, verbose_name='filter fabric allowed'),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_price_allowed',
            field=models.BooleanField(default=True, verbose_name='filter price allowed'),
        ),
        migrations.AddField(
            model_name='category',
            name='filter_size_allowed',
            field=models.BooleanField(default=True, verbose_name='filter size allowed'),
        ),
    ]
