# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20160125_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='disabled',
            field=models.BooleanField(default=False, help_text='disabled because of tariff', verbose_name='disabled'),
        ),
    ]
