# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_tariff_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(help_text='roubles per day', verbose_name='price'),
        ),
    ]
