# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('description', models.CharField(max_length=512, verbose_name='description')),
                ('sum', models.FloatField(verbose_name='sum')),
                ('operation_type', models.CharField(choices=[('payment', 'payment'), ('daily_write_off', 'daily write off'), ('other', 'other')], default='other', max_length=15, verbose_name='operation type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'balance log',
                'verbose_name': 'operation',
            },
        ),
    ]
