# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendFlatpage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('browser_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='browser title')),
                ('meta_description', models.TextField(blank=True, max_length=512, null=True, verbose_name='meta description')),
            ],
            options={
                'verbose_name': 'flat page',
                'verbose_name_plural': 'flat pages',
            },
            bases=('flatpages.flatpage', models.Model),
        ),
    ]
