# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_tariff_is_default'),
        ('user', '0002_auto_20160105_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuser',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff.Tariff', verbose_name='tariff'),
        ),
    ]
