# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_marketplaceuser_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuser',
            name='balanсe',
            field=models.FloatField(default=0, verbose_name='balanсe'),
        ),
    ]
