# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_marketplaceuser_balanсe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceuser',
            old_name='balanсe',
            new_name='balance',
        ),
    ]
