# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160105_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
