# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='e.g. Yandex-validator', max_length=256, null=True, verbose_name='description')),
                ('path', models.CharField(help_text='relative to site root. E.g. /123456789.html', max_length=128, verbose_name='path')),
                ('content_type', models.CharField(default='text/plain', max_length=128, verbose_name='content_type')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
            options={
                'verbose_name_plural': 'SEO files',
                'verbose_name': 'SEO file',
                'ordering': ['path'],
            },
        ),
    ]
