# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20160105_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
