# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160106_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(blank=True, choices=[('PC', 'Яндекс.Деньги'), ('AC', 'Банковская карта')], default='AC', max_length=2, null=True, verbose_name='payment type'),
        ),
    ]
